### ISSUE TITLE
New project fails to npm install 

### ISSUE THREAD

**Issue by Asgaroth** [gatsbyjs/gatsby-starter-wordpress-blog#19]
I was just following the instructions at 

`gatsby new  some-blog https://github.com/gatsbyjs/gatsby-starter-wordpress-blog`

But npm fails to install with

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!   peer react@"^16.9.0 || ^17.0.0" from gatsby@4.0.2
npm ERR!   node_modules/gatsby
npm ERR!     gatsby@"^4.0.0" from the root project
npm ERR!     peer gatsby@"^4.0.0-next" from gatsby-plugin-image@2.0.0
npm ERR!     node_modules/gatsby-plugin-image
npm ERR!       gatsby-plugin-image@"^2.0.0" from the root project
npm ERR!       1 more (gatsby-source-wordpress)
npm ERR!     11 more (gatsby-plugin-sharp, gatsby-source-filesystem, ...)
npm ERR!   8 more (react-dom, gatsby-plugin-image, gatsby-plugin-offline, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.13.0 || ^0.14.0 || ^15.0.0 || ^16.0.0" from react-side-effect@1.2.0
npm ERR! node_modules/react-helmet/node_modules/react-side-effect
npm ERR!   react-side-effect@"^1.1.0" from react-helmet@5.2.1
npm ERR!   node_modules/react-helmet
npm ERR!     react-helmet@"^5.2.1" from the root project
npm ERR!     1 more (gatsby-plugin-react-helmet)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Comment by hansdb** [comment]
Changed react-helmet version from 5.2.1 to 6.1.0 (latest) in package.json fixes the npm install issue. Not sure if it is fully backwards compatible with v5.

**Comment by bzx** [comment]
I have a similar problem – after following the guide there's a bunch of npm errors shown, and running `gatsby develop` gets stuck. Looks like this project is abandoned or something... I've tried different methods of adding gatsby-source-wordpress (from scratch, from a starter) and it all fails or gets stuck. How can this be advertised as "working" when it's not?

**Comment by tekindermisel** [comment]
hello @Asgaroth, in order to make it work you need to do two things, after you run that command:
1. Go into directory "some-blog" and in the package.json reduce react and react-dom to 16.0.1
2. Run npm install "npm i acorn --dev"

After that, check with "npm run start" or "yarn start" to spin up the local server.

**Comment by PiX06** [comment]
> 

That doesn't work for me, this is my package.json:

```
{
  "name": "gatsby-starter-wordpress-blog",
  "private": true,
  "description": "A starter for a blog powered by Gatsby and Markdown",
  "version": "1.0.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com> and Tyler Barnes <tylerdbarnes@gmail.com>",
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  },
  "homepage": "https://github.com/gatsbyjs/gatsby-starter-blog#readme",
  "keywords": [
    "gatsby"
  ],
  "license": "0BSD",
  "main": "n/a",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/gatsbyjs/gatsby-starter-blog.git"
  },
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "gatsby": "^4.0.0",
    "gatsby-plugin-image": "^2.0.0",
    "gatsby-plugin-manifest": "^4.0.0",
    "gatsby-plugin-offline": "^5.0.0",
    "gatsby-plugin-react-helmet": "^5.0.0",
    "gatsby-plugin-sharp": "^4.0.0",
    "gatsby-source-filesystem": "^4.0.0",
    "gatsby-source-wordpress": "^6.0.0",
    "gatsby-transformer-sharp": "^4.0.0",
    "html-react-parser": "^1.1.1",
    "lodash": "^4.17.20",
    "postcss": "^8.2.10",
    "react": "^16.0.1",
    "react-dom": "^16.0.1",
    "react-helmet": "^5.2.1",
    "typeface-merriweather": "1.1.13",
    "typeface-montserrat": "1.1.13"
  },
  "devDependencies": {
    "dumper.js": "^1.3.1",
    "prettier": "2.2.1"
  }
}
```

And running `npm i acorn --dev` gives this output:

```
vagrant@homestead:/var/www/wp-gatsby/gatsby$ npm i acorn --dev
npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
npm ERR! code 1
npm ERR! path /var/www/wp-gatsby/gatsby/node_modules/gatsby-cli
npm ERR! command failed
npm ERR! command sh -c node scripts/postinstall.js
npm ERR! internal/modules/cjs/loader.js:316
npm ERR!       throw err;
npm ERR!       ^
npm ERR!
npm ERR! Error: Cannot find module '/var/www/wp-gatsby/gatsby/node_modules/chalk/source'. Please verify that the package.json has a valid "main" entry
npm ERR!     at tryPackage (internal/modules/cjs/loader.js:308:19)
npm ERR!     at Function.Module._findPath (internal/modules/cjs/loader.js:521:18)
npm ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
npm ERR!     at Module.require (internal/modules/cjs/loader.js:957:19)
npm ERR!     at require (internal/modules/cjs/helpers.js:88:18)
npm ERR!     at Object.<anonymous> (/var/www/wp-gatsby/gatsby/node_modules/gatsby-cli/scripts/postinstall.js:1:15)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:1068:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:933:32) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   path: '/var/www/wp-gatsby/gatsby/node_modules/chalk/package.json',
npm ERR!   requestPath: 'chalk'
npm ERR! }
```

**Comment by peiche** [comment]
Alternatively, you can run `npm install --legacy-peer-deps` to leave the React versions as they are in this repo. That's what I did, and it installed everything successfully.
